name: Build and test

on:
  push:
    # all branches
  pull_request:
    # all branches

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Opendylan
        uses: dylan-lang/install-opendylan@v3

      - name: Add zlib dev dependency
        run: sudo apt-get install -y zlib1g-dev

      - name: Download dependencies
        run: dylan update

      - name: Build tests
        run: dylan build zlib-test-suite

      - name: Run tests
        run: _build/bin/zlib-test-suite --progress none --report surefire > _build/TEST-zlib.xml

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: '**/_build/TEST-*.xml'
